# This file was generated by GoReleaser. DO NOT EDIT.
cask "hint" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "ddcc5fed8398917c8cf41fcc05b56cc924203578b065737cb5ca5d2e5f7e1cad"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ce836e45af4ede19a07fac01f077cca9a236c0a7aa9121612b98546810694468"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ffd8d78c994ae922c26a8225ee068927a4d6cd6a7c3d5ee524e8ca4db655b0b0"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3ff25fe0d8e6b99d410088ff3928a7f23f906735c200aa1bd03935ba6c804a5c"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hint"
  desc "The global command-line tool for Hintoric"
  homepage "https://hintoric.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hint"

  # No zap stanza required

end
