# This file was generated by GoReleaser. DO NOT EDIT.
cask "hint" do
  binary "hint-build"

  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1f46a05c0ece08250c19d04544d3874a8a62141036bdb81f8b1876fd40ffb52e"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1033f5e751456394d622bb9b5bd64542317e8a7f9986e182ba9b6cbf9ae0efb2"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58bb6a52bb26f23348dac74e804a0e7b309f455db155ffca6860de6d8b6f5323"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1bce23a8b491e2966bf78b0a47b7b2b2a132c3d99d368ab4829bf27cde40fe85"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hint"
  desc "Hintoric command-line tool — host CLI with a signed plugin system"
  homepage "https://github.com/hintoric/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hint"

  # No zap stanza required

end
