# This file was generated by GoReleaser. DO NOT EDIT.
cask "hint" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "a2349a708f7830195c93b2f394559748b7d4f7c05c5615df7af28fb0b0bcd61e"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1ac9c9eb087ed1003734a46a9f322d34393babe355b2b833c986ebd1a87cac32"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7bdd738e4992c5f94bd57ba856e45e31e2db95d901bc9f3d9f42274fc85bf82f"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f1565049e585f82b63ec7e848751b2ee61e370831ff0227b3ab9e5dafbd65a3a"
      url "https://github.com/hintoric/cli/releases/download/v#{version}/hint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hint"
  desc "The global command-line tool for Hintoric"
  homepage "https://hintoric.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hint"

  # No zap stanza required

end
